/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * file-service
 * OpenAPI spec version: 1.0.0
 */
import type { FileType } from './fileType';

export interface CreateFileRequest {
  name: string;
  type: FileType;
  parentId?: number;
  content?: string;
}
