/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Notebook API
 * REST API for notebooks, pages, categories, and workspaces.
 * OpenAPI spec version: 1.0
 */

/**
 * A notebook containing pages.
 */
export interface DtoCreateNotebookRequest {
  collaboratorIds?: string[];
  description?: string;
  isPublic?: boolean;
  tags?: string[];
  /** @minLength 1 */
  title: string;
  workspaceId?: string;
}
