/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * file-service
 * OpenAPI spec version: 1.0.0
 */

export type FileType = typeof FileType[keyof typeof FileType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileType = {
  file: 'file',
  folder: 'folder',
} as const;
