/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * file-service
 * OpenAPI spec version: 1.0.0
 */
import type { FileType } from './fileType';

export interface FileDTO {
  id: number;
  name: string;
  type: FileType;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  parentId?: number | null;
}
