/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * file-service
 * OpenAPI spec version: 1.0.0
 */
import type { FileDTO } from './fileDTO';

/**
 * @nullable
 */
export type GetFileById200 = FileDTO | null;
