/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * file-service
 * OpenAPI spec version: 1.0.0
 */

export * from './createFileRequest';
export * from './deleteFile200';
export * from './fileDTO';
export * from './fileType';
export * from './getFileById200';
export * from './postFile200';
export * from './putFile200';
export * from './updateFileRequest';