/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Notebook API
 * REST API for notebooks, pages, categories, and workspaces.
 * OpenAPI spec version: 1.0
 */

/**
 * Notebook category with metadata.
 */
export interface ModelsCategory {
  color?: string;
  createdAt?: number;
  description?: string;
  id?: string;
  name?: string;
  updatedAt?: number;
  workspaceId?: string;
}
