/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Notebook API
 * REST API for notebooks, pages, categories, and workspaces.
 * OpenAPI spec version: 1.0
 */
import type { ModelsPage } from './modelsPage';

/**
 * A notebook containing pages.
 */
export interface ModelsNotebook {
  collaboratorIds?: string[];
  /** Timestamps (managed by GORM) */
  createdAt?: string;
  description?: string;
  id?: string;
  isPublic?: boolean;
  lastAccessedAt?: string;
  ownerId?: string;
  /** Has Many */
  pages?: ModelsPage[];
  /** JSON fields (let GORM marshal automatically) */
  tags?: string[];
  title?: string;
  updatedAt?: string;
  /** Relationships */
  workspaceId?: string;
}
