/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Notebook API
 * REST API for notebooks, pages, categories, and workspaces.
 * OpenAPI spec version: 1.0
 */
import type { ModelsNotebook } from './modelsNotebook';

/**
 * A workspace that contains notebooks and categories.
 */
export interface ModelsWorkspace {
  id?: string;
  notebooks?: ModelsNotebook[];
  userId?: string;
}
