/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Notebook API
 * REST API for notebooks, pages, categories, and workspaces.
 * OpenAPI spec version: 1.0
 */
import type { ModelsPageContent } from './modelsPageContent';

/**
 * A content page inside a notebook.
 */
export interface ModelsPage {
  content?: ModelsPageContent;
  createdAt?: number;
  id?: string;
  lastExecutedAt?: number;
  /** relationships */
  notebookId?: string;
  order?: number;
  title?: string;
  updatedAt?: number;
}
