/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Notebook API
 * REST API for notebooks, pages, categories, and workspaces.
 * OpenAPI spec version: 1.0
 */

/**
 * A notebook containing pages.
 */
export interface ModelsNotebook {
  collaboratorIds?: string[];
  createdAt?: number;
  description?: string;
  id?: string;
  isPublic?: boolean;
  lastAccessedAt?: number;
  ownerId?: string;
  tags?: string[];
  title?: string;
  updatedAt?: number;
  workspaceId?: string;
}
