/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Notebook API
 * REST API for notebooks, pages, categories, and workspaces.
 * OpenAPI spec version: 1.0
 */

export type PostNotebooks400 = {[key: string]: string};
