/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedNotebook: typeof import('./components/AnimatedNotebook.vue')['default']
    AppLayout: typeof import('./components/AppLayout.vue')['default']
    ColorGridPicker: typeof import('./components/ColorGridPicker.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    EditorToolbar: typeof import('./components/EditorToolbar.vue')['default']
    FeaturedBanner: typeof import('./components/FeaturedBanner.vue')['default']
    NavToolbar: typeof import('./components/NavToolbar.vue')['default']
    NotebookCard: typeof import('./components/NotebookCard.vue')['default']
    Orb: typeof import('./components/Orb.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextType: typeof import('./components/TextType.vue')['default']
    ToolbarDropdown: typeof import('./components/ToolbarDropdown.vue')['default']
    VuePaintSample: typeof import('./components/VuePaintSample.vue')['default']
  }
}
