/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Notebook API
 * REST API for notebooks, pages, categories, and workspaces.
 * OpenAPI spec version: 1.0
 */
import { customAxios } from './custom-axios';
/**
 * Notebook category with metadata.
 */
export interface ModelsCategory {
  color?: string;
  createdAt?: number;
  description?: string;
  id?: string;
  name?: string;
  updatedAt?: number;
  workspaceId?: string;
}

/**
 * A notebook containing pages.
 */
export interface ModelsNotebook {
  collaboratorIds?: string[];
  createdAt?: number;
  description?: string;
  id?: string;
  isPublic?: boolean;
  lastAccessedAt?: number;
  ownerId?: string;
  tags?: string[];
  title?: string;
  updatedAt?: number;
  workspaceId?: string;
}

export type ModelsPageContent = { [key: string]: unknown };

/**
 * A content page inside a notebook.
 */
export interface ModelsPage {
  content?: ModelsPageContent;
  createdAt?: number;
  id?: string;
  lastExecutedAt?: number;
  notebookId?: string;
  order?: number;
  title?: string;
  updatedAt?: number;
}

/**
 * A workspace that contains notebooks and categories.
 */
export interface ModelsWorkspace {
  categories?: ModelsCategory[];
  id?: string;
  notebooks?: ModelsNotebook[];
  userId?: string;
}

export type GetNotebooksId404 = {[key: string]: string};

export type PostNotebooksIdPagesBody = { [key: string]: unknown };

export type PostNotebooksIdPages400 = {[key: string]: string};

export type GetPagesId404 = {[key: string]: string};

export type PostWorkspacesBody = {[key: string]: string};

export const getNotebookAPI = () => {
/**
 * @summary List categories
 */
const getCategories = (
    
 ) => {
      return customAxios<ModelsCategory[]>(
      {url: `/categories`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Create a category
 */
const postCategories = (
    modelsCategory: ModelsCategory,
 ) => {
      return customAxios<ModelsCategory>(
      {url: `/categories`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: modelsCategory
    },
      );
    }
  
/**
 * @summary List all notebooks
 */
const getNotebooks = (
    
 ) => {
      return customAxios<ModelsNotebook[]>(
      {url: `/notebooks`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Create a notebook
 */
const postNotebooks = (
    modelsNotebook: ModelsNotebook,
 ) => {
      return customAxios<ModelsNotebook>(
      {url: `/notebooks`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: modelsNotebook
    },
      );
    }
  
/**
 * @summary Get a notebook by ID
 */
const getNotebooksId = (
    id: string,
 ) => {
      return customAxios<ModelsNotebook>(
      {url: `/notebooks/${id}`, method: 'GET'
    },
      );
    }
  
/**
 * Alias for GetPagesByNotebook (kept for compatibility)
 * @summary Get pages by notebook
 */
const getNotebooksIdPages = (
    id: string,
 ) => {
      return customAxios<ModelsPage[]>(
      {url: `/notebooks/${id}/pages`, method: 'GET'
    },
      );
    }
  
/**
 * Creates a new page belonging to a notebook
 * @summary Create a page in a notebook
 */
const postNotebooksIdPages = (
    id: string,
    postNotebooksIdPagesBody: PostNotebooksIdPagesBody,
 ) => {
      return customAxios<ModelsPage>(
      {url: `/notebooks/${id}/pages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postNotebooksIdPagesBody
    },
      );
    }
  
/**
 * Returns all pages from all notebooks
 * @summary Get all pages
 */
const getPages = (
    
 ) => {
      return customAxios<ModelsPage[]>(
      {url: `/pages`, method: 'GET'
    },
      );
    }
  
/**
 * Returns a single page by its ID
 * @summary Get a page by ID
 */
const getPagesId = (
    id: string,
 ) => {
      return customAxios<ModelsPage>(
      {url: `/pages/${id}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary List all workspaces
 */
const getWorkspaces = (
    
 ) => {
      return customAxios<ModelsWorkspace[]>(
      {url: `/workspaces`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Create a workspace
 */
const postWorkspaces = (
    postWorkspacesBody: PostWorkspacesBody,
 ) => {
      return customAxios<ModelsWorkspace>(
      {url: `/workspaces`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postWorkspacesBody
    },
      );
    }
  
return {getCategories,postCategories,getNotebooks,postNotebooks,getNotebooksId,getNotebooksIdPages,postNotebooksIdPages,getPages,getPagesId,getWorkspaces,postWorkspaces}};
export type GetCategoriesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookAPI>['getCategories']>>>
export type PostCategoriesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookAPI>['postCategories']>>>
export type GetNotebooksResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookAPI>['getNotebooks']>>>
export type PostNotebooksResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookAPI>['postNotebooks']>>>
export type GetNotebooksIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookAPI>['getNotebooksId']>>>
export type GetNotebooksIdPagesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookAPI>['getNotebooksIdPages']>>>
export type PostNotebooksIdPagesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookAPI>['postNotebooksIdPages']>>>
export type GetPagesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookAPI>['getPages']>>>
export type GetPagesIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookAPI>['getPagesId']>>>
export type GetWorkspacesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookAPI>['getWorkspaces']>>>
export type PostWorkspacesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookAPI>['postWorkspaces']>>>
