/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * notebook-service
 * OpenAPI spec version: 1.0.0
 */
import type {
  AuthResponse,
  CreateNotebook200,
  CreateNotebookRequest,
  CreatePage200,
  CreatePageRequest,
  CreateWorkspace200,
  CreateWorkspaceRequest,
  DeleteNotebook200,
  DeletePage200,
  DeleteWorkspace200,
  GetNotebooksParams,
  GetPagesParams,
  LoginRequest,
  NotebookDTO,
  PageDTO,
  RegisterRequest,
  UpdateNotebook200,
  UpdateNotebookRequest,
  UpdatePage200,
  UpdatePageRequest,
  UpdateWorkspace200,
  UpdateWorkspaceRequest,
  WorkspaceDTO
} from './model';

import { customAxios } from './custom-axios';
export const getNotebookService = () => {
const getWorkspaces = (
    
 ) => {
      return customAxios<WorkspaceDTO[]>(
      {url: `/workspaces`, method: 'GET'
    },
      );
    }
  
const createWorkspace = (
    createWorkspaceRequest: CreateWorkspaceRequest,
 ) => {
      return customAxios<CreateWorkspace200>(
      {url: `/workspaces`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWorkspaceRequest
    },
      );
    }
  
const updateWorkspace = (
    id: number,
    updateWorkspaceRequest: UpdateWorkspaceRequest,
 ) => {
      return customAxios<UpdateWorkspace200>(
      {url: `/workspaces/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateWorkspaceRequest
    },
      );
    }
  
const deleteWorkspace = (
    id: number,
 ) => {
      return customAxios<DeleteWorkspace200>(
      {url: `/workspaces/${id}`, method: 'DELETE'
    },
      );
    }
  
const getPages = (
    params?: GetPagesParams,
 ) => {
      return customAxios<PageDTO[]>(
      {url: `/pages`, method: 'GET',
        params
    },
      );
    }
  
const createPage = (
    createPageRequest: CreatePageRequest,
 ) => {
      return customAxios<CreatePage200>(
      {url: `/pages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPageRequest
    },
      );
    }
  
const updatePage = (
    id: number,
    updatePageRequest: UpdatePageRequest,
 ) => {
      return customAxios<UpdatePage200>(
      {url: `/pages/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updatePageRequest
    },
      );
    }
  
const deletePage = (
    id: number,
 ) => {
      return customAxios<DeletePage200>(
      {url: `/pages/${id}`, method: 'DELETE'
    },
      );
    }
  
const getNotebooks = (
    params?: GetNotebooksParams,
 ) => {
      return customAxios<NotebookDTO[]>(
      {url: `/notebooks`, method: 'GET',
        params
    },
      );
    }
  
const createNotebook = (
    createNotebookRequest: CreateNotebookRequest,
 ) => {
      return customAxios<CreateNotebook200>(
      {url: `/notebooks`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createNotebookRequest
    },
      );
    }
  
const updateNotebook = (
    id: number,
    updateNotebookRequest: UpdateNotebookRequest,
 ) => {
      return customAxios<UpdateNotebook200>(
      {url: `/notebooks/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateNotebookRequest
    },
      );
    }
  
const deleteNotebook = (
    id: number,
 ) => {
      return customAxios<DeleteNotebook200>(
      {url: `/notebooks/${id}`, method: 'DELETE'
    },
      );
    }
  
const register = (
    registerRequest: RegisterRequest,
 ) => {
      return customAxios<AuthResponse>(
      {url: `/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerRequest
    },
      );
    }
  
const login = (
    loginRequest: LoginRequest,
 ) => {
      return customAxios<AuthResponse>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest
    },
      );
    }
  
return {getWorkspaces,createWorkspace,updateWorkspace,deleteWorkspace,getPages,createPage,updatePage,deletePage,getNotebooks,createNotebook,updateNotebook,deleteNotebook,register,login}};
export type GetWorkspacesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookService>['getWorkspaces']>>>
export type CreateWorkspaceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookService>['createWorkspace']>>>
export type UpdateWorkspaceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookService>['updateWorkspace']>>>
export type DeleteWorkspaceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookService>['deleteWorkspace']>>>
export type GetPagesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookService>['getPages']>>>
export type CreatePageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookService>['createPage']>>>
export type UpdatePageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookService>['updatePage']>>>
export type DeletePageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookService>['deletePage']>>>
export type GetNotebooksResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookService>['getNotebooks']>>>
export type CreateNotebookResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookService>['createNotebook']>>>
export type UpdateNotebookResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookService>['updateNotebook']>>>
export type DeleteNotebookResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookService>['deleteNotebook']>>>
export type RegisterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookService>['register']>>>
export type LoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotebookService>['login']>>>
